// This file is automatically generated. Do not modify it manually.
// You can publish a new version of this file by running the 'firebase-framework-tools' CLI.
// If you need to make changes to the configuration, edit the 'docs/backend.json' file.
// Then run the 'firebase-framework-tools' CLI to apply the changes.
//
// You can strongly type the configuration by creating a 'lib/firebase-config.d.ts'
// file with the following content:
//
// declare module "firebase-config" {
//   export const firebaseConfig: {
//     apiKey: string;
//     authDomain: string;
//     projectId: string;
//     storageBucket: string;
//     messagingSenderId: string;
//     appId: string;
//     measurementId: string;
//   };
// }

export const firebaseConfig = {
  apiKey: "placeholder-api-key",
  authDomain: "placeholder-auth-domain",
  projectId: "placeholder-project-id",
  storageBucket: "placeholder-storage-bucket",
  messagingSenderId: "placeholder-messaging-sender-id",
  appId: "placeholder-app-id",
  measurementId: "placeholder-measurement-id",
};
